version: 2.1

parameters:
  build:
    type: boolean

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  main:
    jobs:
      - say-hello